### ISSUE TITLE
API v2 - Coordination issue and checklist

### ISSUE THREAD

**Issue by thi4go** [decred/dcrtime#59]
# dcrtime `api/v2`

This issue will be used to track down the improvements and development needed on version two of dcrtime's api.

## Tasks

These are the requirements tracked until now:

- [x] Version the `api/` dir with go modules (wip)
- [ ] Convert `[]byte` data to `string` with hex encoded data
- [x] Route for timestamping single digest, needed for JS-less gui app
- [ ] Route for checking the next anchor time

## Routes on `api/v2`

```
/v2/timestamp
/v2/timestamps
/v2/verify
/v2/next (or decided naming for next anchor time)
```
where
`/v2/timestamp` accepts a single string digest
`/v2/timestamps` is the same as `/v1/timestamp`
`/v2/verify` is the same as `/v1/verify/`
`/v2/next` returns the next anchor time

**Comment by marcopeereboom** [comment]
Can this be closed @thi4go?

**Comment by thi4go** [comment]
Yes @marcopeereboom , closing it.
